image:
    file: .gitpod.Dockerfile

tasks:
    # - init: |

    - command: |
          mix archive.install --force hex phx_new
          mix deps.get

vscode:
    extensions:
        - redhat.vscode-yaml
        - yy0931.vscode-sqlite3-editor
        - gruntfuggly.todo-tree
        - phoenixframework.phoenix
        - jakebecker.elixir-ls
